### ISSUE TITLE
Install Extension step returns success after failing

### ISSUE THREAD

**Issue by eduardomhg** [Microsoft/vsts-extension-build-release-tasks#31]
After executing the Install Extension step it reported success while having this console output:

`error: Error: Failed Request: Conflict(409) - TF1590010: Extension eduardomhg.custom-build-tasks is already installed in this account. `

**Comment by jessehouwing** [comment]
That is expected behavior.

We are actively suppressing this error until tfx no longer throws this as
an error but as a warning again (it used to do so). Since the extension is
already installed, the intent of the install task has been accomplish and
we do no get consider this a real error because of that.

On Dec 19, 2016 18:47, "Eduardo Hernández" <notifications@github.com> wrote:

After executing the Install Extension step it reported success while having
this console output:

error: Error: Failed Request: Conflict(409) - TF1590010: Extension
eduardomhg.custom-build-tasks is already installed in this account.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vsts-extension-build-release-tasks/issues/31>,
or mute the thread

**Comment by eduardomhg** [comment]
So what would be the preferred way of setting up a build pipeline that continuously builds an extension and automatically installs it on a set of accounts (creating a new version number for each build?

**Comment by jessehouwing** [comment]
Your setup is fine. If the extension gets uninstalled, this task will reinstall it. But if the extension is installed to all accounts, it will remain so and the new version will automatically become available to these accounts.

The Share and Install task are there for convenience, should you decide to delete a private version of the extension from the marketplace, their default share and install status will be reset, these tasks will then restore them to what the pipeline expects. In every other case, they're not going to do anything, except complain that the extension has already been shared or has already been installed to the account.

I've built in logic to ignore these errors, awaiting a proper fix in tfs-cli. See also: #12.
