### ISSUE TITLE
"Extension Tag" not working if extension id is taken from manifest

### ISSUE THREAD

**Issue by FlexiGit** [Microsoft/vsts-extension-build-release-tasks#40]
In my build definition I have two steps that build the "same" package. One is intended for deploying to a test VSTS account and the other for being published to the production accounts.

To keep the build tasks simple I want to use  as much information from the manifest as possible.

As the title suggests, if I don't override the extension id, the "Extension Tag" setting is ignored and the second step overrides the output vsix from the first one.

**Comment by jessehouwing** [comment]
This is expected. Tag is only applied when the extension id is set.

This is currently a limitation of how the override is computed.

You could do a publish from vsix and override the tag value in there, it
will use the value from the source vsix manifest.

On Jan 25, 2017 10:58 AM, "FlexiGit" <notifications@github.com> wrote:

In my build definition I have two steps that build the "same" package. One
is intended for deploying to a test VSTS account and the other for being
published to the production accounts.

To keep the build tasks simple I want to use as much information from the
manifest as possible.

As the title suggests, if I don't override the extension id, the "Extension
Tag" setting is ignored and the second step overrides the output vsix from
the first one.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vsts-extension-build-release-tasks/issues/40>,
or mute the thread
