### ISSUE TITLE
Publish task not piping out all output, the --json output is less verbose.

### ISSUE THREAD

**Issue by masters3d** [Microsoft/vsts-extension-build-release-tasks#55]
I am able to build and publish manually but not with the plug in. 

I created the token with all scoped and then created other token with the recommended scope and still same response.

I tried publishing from the manifest and packaging up then publishing the package. Same results.

```
2017-12-07T01:25:26.4198066Z ##[section]Starting: Publish Extension
2017-12-07T01:25:26.4203685Z ==============================================================================
2017-12-07T01:25:26.4203986Z Task         : Publish Extension
2017-12-07T01:25:26.4204274Z Description  : Publish a Team Services extension to the Visual Studio Marketplace
2017-12-07T01:25:26.4204536Z Version      : 1.1.44
2017-12-07T01:25:26.4204769Z Author       : Microsoft Corporation
2017-12-07T01:25:26.4204994Z Help         : 
2017-12-07T01:25:26.4205240Z ==============================================================================
2017-12-07T01:25:26.8394617Z Checking tfx under: d:\a\_tools\tfx.cmd
2017-12-07T01:25:26.8429052Z Could not find tfx command. Preparing to install it under: d:\a\_tools\
2017-12-07T01:25:27.4034049Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install tfx-cli@0.4.8 --prefix d:\a\_tools\"
2017-12-07T01:25:51.0639172Z npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
2017-12-07T01:26:37.3044560Z npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
2017-12-07T01:27:12.9307278Z d:\a\_tools\tfx -> d:\a\_tools\node_modules\tfx-cli\_build\tfx-cli.js
```

```
: Received response 401 (Not Authorized). Check that your personal access token is correct and hasn't expired.
```

```json
{
    "manifestVersion": 1,
    "id": "build-task",
    "name": "Build Task",
    "version": "0.9.9",
    "publisher": "mypublisher",
    "targets": [
        {
            "id": "Microsoft.VisualStudio.Services"
        }
    ],    
    "description": "Tools for building with Fabrikam. Includes one build task.",
    "categories": [
        "Build and release"
    ],
    "icons": {
        "default": "images/extension-icon.png"        
    },
    "files": [
        {
            "path": "buildtask"
        }
    ],
    "contributions": [
        {
            "id": "custom-build-task",
            "type": "ms.vss-distributed-task.task",
            "targets": [
                "ms.vss-distributed-task.tasks"
            ],
            "properties": {
                "name": "buildtask"
            }
        }
    ]
}
```

**Comment by jessehouwing** [comment]
Please file  the issue over at the tfs cli project. There is really nothing
much I can do about the authentication process.

**Comment by masters3d** [comment]
TFX's error is more descriptive:
```
Checking if this extension is already published
It isn't, create a new extension.
error: Received response 401 (Not Authorized). Check that your personal access token is correct and hasn't expired.
```

**Comment by jessehouwing** [comment]
There is still very little I can do for you. Please contact marketplace
support or file an issue in the tfs-cli project.

The developers of the command line tools are not monitoring this repo and
there isn't much I can do. We just invoke the cli tools and pipe the output
to the agent logs.

On Dec 7, 2017 22:15, "Cheyo Jimenez" <notifications@github.com> wrote:

TFX's error is more descriptive:

Checking if this extension is already published
It isn't, create a new extension.
error: Received response 401 (Not Authorized). Check that your
personal access token is correct and hasn't expired.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vsts-extension-build-release-tasks/issues/55#issuecomment-350096413>,
or mute the thread

**Comment by masters3d** [comment]
I found the issue. This repo's Task extension is using the JSON output which does not output all what the regular client output does. 

See these lines:
https://github.com/Microsoft/vsts-extension-build-release-tasks/blob/master/BuildTasks/PublishExtension/PublishExtension.ts#L117

https://github.com/Microsoft/vsts-extension-build-release-tasks/blob/master/BuildTasks/PublishExtension/PublishExtension.ts#L9


Sample:  Regular output
```
C:\extension>tfx extension publish  --auth-type pat
TFS Cross Platform Command Line Interface v0.4.11
Copyright Microsoft Corporation
> Personal access token:
Checking if this extension is already published
It isn't, create a new extension.
error: Received response 401 (Not Authorized). Check that your personal access token is correct and hasn't expired.
```
-- JSON option the publish task is using.
```
C:\extension>tfx extension publish --json --auth-type pat
> Personal access token:
error: Received response 401 (Not Authorized). Check that your personal access token is correct and hasn't expired.
```

**Comment by jessehouwing** [comment]
That is by design. We need the Jason in order to extract certain values. The tool can't return anything else on the output stream, as it would not be valid json.

So we only render the error stream. Still not sure what you are trying to read from output. It always checks the existence of the extension and it always creates a new one if it doesn't exist already. Requires the same permissions.

This is not the error you're looking for.

**Comment by jessehouwing** [comment]
You still want the tfx tool to set a better error message in the json object or output that to the error stream so I can render it.

**Comment by masters3d** [comment]
That is fair. Closing in favor for better error message at tfx.
