### ISSUE TITLE
Add `--trace-level debug`

### ISSUE THREAD

**Issue by masters3d** [Microsoft/vsts-extension-build-release-tasks#56]
Request to add debug flag just added to the JSON output in tfs-cli
https://github.com/Microsoft/tfs-cli/issues/243

Reference.
#55

**Comment by nickhara** [comment]
I was hitting an error I could not reproduce locally (due to using a different version of tfx-cli) - but I could not figure out how to enable tfx tracing through the task.  Additionally, it would be really nice to have a more verbose mode that surfaces the actual tfx-cli commands that are being executed.
