### ISSUE TITLE
Publish Task additional arguments not honored

### ISSUE THREAD

**Issue by nickhara** [Microsoft/vsts-extension-build-release-tasks#57]
I've been trying to debug an issue where tfx is failing to validate our extension during publishing.  The task is failing with this semi-cryptic error:
`2017-12-20T19:16:57.8041612Z error: Error: Validation timed out. There may be a problem validating your extension. Please try again later.`
`2017-12-20T19:16:57.8261928Z ##[error]tfx failed with error: Error: d:\a\_tools\tfx.cmd failed with return code: 4294967295`

Looking at the task.json, I see:
`{   "name": "arguments",
      "type": "string",
      "label": "Arguments",
      "defaultValue": "",
      "helpMarkDown": "Additional arguments passed to the package and publishing tool.",
      "required": false,
      "groupName": "advanced"
    }`
However, I could not find where these arguments were processed or added to the tfx command.

In order to debug further, I added '--trace-level debug' to the 'Arguments' under the Advanced variable group.  However, I did not see any additional debug output.

Side note - looking at the tfx-cli history, I believe the underlying issue is related to a change to add faster validation values for non-public releases.

**Comment by jessehouwing** [comment]
We're redirecting most output, since we're forcing `tfx` to produce a json result (in order to process the results), this suppresses a lot of the output, unfortunately. 

I'm testing a version with the extra checkboxes you suggested.

@willsmythe do you know if there is a way I can for the marketplace to timeout or to force an extended validation. Testing is pretty hard since the behavior is hard to reproduce consistently on my end...

**Comment by nickhara** [comment]
Thanks Jesse!
