### ISSUE TITLE
Honor proxy settings

### ISSUE THREAD

**Issue by axelheer** [Microsoft/vsts-extension-build-release-tasks#88]
PR #62 already introduced proxy support by using `getHttpProxyConfiguration` in order to get the proxy settings used by the current agent.

Somehow the calls `common.setProxy()` are still commented out? Why?

Currently the task is unable to install the `tfx-cli` package behind a corporate proxy...

cc @jessehouwing

**Comment by jessehouwing** [comment]
Primary reason is that the way tfs-cli and node and Windows and all handle the exclusions list differently, they handle IP ranges differently, so it works for basic setup, but it fails in more complex ones.

After checking back with Microsoft we decided to let proxy configuration in the hands of the agent admins and not in the task.

Reasons for this are:
* Since we need to override environment variables, we may be breaking other Node based tasks after us.
* Since the proxy exclusions are different between platforms we'll need to handle all kinds of weird conversions and I don't want to maintain these
* Since this can be solved by the agent admin by setting the System level environment variables easily, there is a workaround available
* Since this can be solved by the Build administrator by setting these at the Build Definition variable level, there is a workaround available.

I've removed the proxy code from the latest build which will be merged soon.

**Comment by axelheer** [comment]
https://github.com/Microsoft/vsts-tasks/blob/17e9161e41df6d30402cd89f71a274b712fdbff4/Tasks/NpmV1/npmtoolrunner.ts#L102-L107

The standard NPM task (by Microsoft) reads the proxy settings of the agent and applys them accordingly, there is no workaround necessary...

Isn't that the idea? The admin configures the proxy settings for the agent only and every tasks does whatever it seems fit to make it work. If the admin has to consider every possible task, it would be much more work and there will be conflicts too.

**Comment by jessehouwing** [comment]
I can't make it work "right", generic proxy config with "everything through proxy" works, but many corps require fancy exclusions and other things. You can configure Node on the machine to handle your proxy correctly, you can set the environment variables, that way the task won't have to deal with it at all. That's currently my preferred stance.

**Comment by axelheer** [comment]
Since I ran into this again, for further reference:

```
- pwsh: |
    Write-Host "##vso[task.setvariable variable=NPM_CONFIG_PROXY;]$env:AGENT_PROXYURL"
    Write-Host "##vso[task.setvariable variable=NPM_CONFIG_HTTPS-PROXY;]$env:AGENT_PROXYURL"
  displayName: 'Setup NPM proxy configuration'

- task: TfxInstaller@3
  inputs:
    version: 'v0.8.x'
  displayName: 'Install TFX'

- pwsh: |
    Write-Host "##vso[task.setvariable variable=NPM_CONFIG_PROXY;]"
    Write-Host "##vso[task.setvariable variable=NPM_CONFIG_HTTPS-PROXY;]"
  displayName: 'Reset NPM proxy configuration'
```

This sets the npm proxy just for the TFX installer...
